// Seed data for the Couch Buddies merch store

export const seedProducts = [
  {
    id: 'prod-1',
    name: 'Classic Couch Buddy Tee',
    description: 'Our signature comfort tee. Made with premium cotton blend for maximum lounge-ability. Features the iconic Couch Buddies logo on the front.',
    price: 34.99,
    category: 'T-Shirts',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Navy'],
    stock: 150,
    featured: true,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop'],
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Couch Buddies Hoodie',
    description: 'Stay cozy in our premium heavyweight hoodie. Soft fleece interior, embroidered logo, and kangaroo pocket. Perfect for movie nights.',
    price: 64.99,
    category: 'Hoodies',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal', 'Forest Green', 'Burgundy'],
    stock: 85,
    featured: true,
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=600&fit=crop'],
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'CB Logo Snapback Cap',
    description: 'Structured snapback with embroidered CB logo. Adjustable strap fits all sizes. Flat brim with premium stitching.',
    price: 29.99,
    category: 'Accessories',
    sizes: ['One Size'],
    colors: ['Black', 'White', 'Orange'],
    stock: 200,
    featured: true,
    images: ['https://images.unsplash.com/photo-1588850561407-ed78c334e67a?w=600&h=600&fit=crop'],
    createdAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Couch Buddies Joggers',
    description: 'Ultra-soft joggers for peak comfort. Tapered fit with elastic waistband and cuffs. Side pockets and back pocket with zip.',
    price: 49.99,
    category: 'Bottoms',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Grey', 'Navy'],
    stock: 120,
    featured: false,
    images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600&h=600&fit=crop'],
    createdAt: '2026-01-25T00:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'CB Cozy Blanket',
    description: 'Premium fleece throw blanket with oversized Couch Buddies branding. 50x60 inches of pure comfort. Machine washable.',
    price: 44.99,
    category: 'Accessories',
    sizes: ['One Size'],
    colors: ['Orange/Black', 'Purple/White'],
    stock: 60,
    featured: true,
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop'],
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'Couch Buddies Mug',
    description: 'Ceramic 15oz mug with wraparound Couch Buddies art. Microwave and dishwasher safe. The perfect Netflix companion.',
    price: 18.99,
    category: 'Accessories',
    sizes: ['One Size'],
    colors: ['Black', 'White'],
    stock: 300,
    featured: false,
    images: ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&h=600&fit=crop'],
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'Limited Edition Varsity Jacket',
    description: 'Premium varsity jacket with leather sleeves and chenille CB patch. Limited run of 200 pieces. Satin lined interior.',
    price: 129.99,
    category: 'Outerwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black/Orange', 'Navy/White'],
    stock: 30,
    featured: true,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=600&fit=crop'],
    createdAt: '2026-02-05T00:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'CB Phone Case',
    description: 'Durable polycarbonate phone case with Couch Buddies artwork. Available for iPhone and Samsung Galaxy models.',
    price: 24.99,
    category: 'Accessories',
    sizes: ['iPhone 15', 'iPhone 14', 'Galaxy S24', 'Galaxy S23'],
    colors: ['Clear', 'Black'],
    stock: 180,
    featured: false,
    images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&h=600&fit=crop'],
    createdAt: '2026-02-08T00:00:00Z',
  },
]

export const seedStaff = [
  {
    id: 'staff-1',
    name: 'Alex Rivera',
    email: 'alex@couchbuddies.com',
    phone: '555-0101',
    role: 'onsite',
    pin: '1111',
    clockedIn: false,
    clockType: null,
    clockHistory: [],
    wallet: { balance: 250.00, transactions: [
      { id: 'wt1', type: 'payment', amount: 250.00, note: 'Weekly pay', from: 'Owner Treasury', time: '2026-02-07T17:00:00Z' }
    ]},
    location: null,
    avatar: 'AR',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'staff-2',
    name: 'Jordan Lee',
    email: 'jordan@couchbuddies.com',
    phone: '555-0102',
    role: 'delivery',
    pin: '2222',
    clockedIn: false,
    clockType: null,
    clockHistory: [],
    wallet: { balance: 180.00, transactions: [
      { id: 'wt2', type: 'payment', amount: 180.00, note: 'Weekly pay', from: 'Owner Treasury', time: '2026-02-07T17:00:00Z' }
    ]},
    location: null,
    avatar: 'JL',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'staff-3',
    name: 'Sam Chen',
    email: 'sam@couchbuddies.com',
    phone: '555-0103',
    role: 'delivery',
    pin: '3333',
    clockedIn: false,
    clockType: null,
    clockHistory: [],
    wallet: { balance: 320.00, transactions: [
      { id: 'wt3', type: 'payment', amount: 320.00, note: 'Weekly pay + tips', from: 'Owner Treasury', time: '2026-02-07T17:00:00Z' }
    ]},
    location: null,
    avatar: 'SC',
    createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'staff-4',
    name: 'Maya Patel',
    email: 'maya@couchbuddies.com',
    phone: '555-0104',
    role: 'onsite',
    pin: '4444',
    clockedIn: false,
    clockType: null,
    clockHistory: [],
    wallet: { balance: 200.00, transactions: [
      { id: 'wt4', type: 'payment', amount: 200.00, note: 'Weekly pay', from: 'Owner Treasury', time: '2026-02-07T17:00:00Z' }
    ]},
    location: null,
    avatar: 'MP',
    createdAt: '2026-01-10T00:00:00Z',
  },
]
